baseURL = 'https://withcodeexample.com/'
languageCode = 'en-us'
title = 'With Code Example'
description= "desc"

theme = "hugo-blog-awesome"

[site]
    title = "Site"

[params]
    description= "Learn Golang, Javascript, Python with code exaples"
    sitename = "Learn With Code Example"
    title = "Golang, Javascript, Python"

[[params.socialIcons]]
    name = "github"
    url = "https://github.com/awesome-blog"

[[params.socialIcons]]
    name = "Rss"
    url = "index.xml"

[params.author]
  intro = "With Code Example"
  description = "Learn Golang, Javascript, Python with Examples"

[[params.sites]]
  name = "Golang With Code Example"
  domain = "https://golang.withcodeexample.com/"

[[params.sites]]
  name = "Javascript With Code Example"
  domain = "https://javascript.withcodeexample.com/"

[[params.sites]]
  name = "Python With Code Example"
  domain = "https://python.withcodeexample.com/"

[[menu.main]]
    name = "Golang"
    url = "https://golang.withcodeexample.com/"
    weight = 1

[[menu.main]]
    name = "Javascript"
    url = "https://javascript.withcodeexample.com/"
    weight = 2

[[menu.main]]
    name = "Python"
    url = "https://python.withcodeexample.com/"
    weight = 2